name: syncerrr
#
on:
  schedule:
    - cron: 25 */10 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  syncc1:
    runs-on: ubuntu-latest
    name: Syncerrr1
    continue-on-error: true
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG1 }}
          EOF
      - name: Transferr1
        run: |
          rclone copy gdrive:"/Transfer/Pahe Final/Pahe Part 1" onedrive1:"/Pahe Part 1" -P --stats 30s --stats-one-line
  syncc2:
    needs : syncc1
    runs-on: ubuntu-latest
    name: Syncerrr2
    continue-on-error: true
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG1 }}
          EOF
      - name: Transferr2
        run: |
          rclone copy gdrive:"/Transfer/Pahe Final/Pahe Part 2" onedrive2:"/Pahe Part 2" -P --stats 30s --stats-one-line
  syncc3:
    needs : syncc2
    runs-on: ubuntu-latest
    name: Syncerrr3
    continue-on-error: true
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG1 }}
          EOF
      - name: Transferr3
        run: |
          rclone copy gdrive:"/Transfer/Sorted/Movies" onedrive3:"/PSA Movies" -P --stats 30s --stats-one-line
  syncc4:
    needs : syncc3
    runs-on: ubuntu-latest
    name: Syncerrr4
    continue-on-error: true
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG1 }}
          EOF
      - name: Transferr4
        run: |
          rclone copy gdrive:"/Transfer/Sorted/TV Shows Part 1" onedrive4:"/PSA TV Part 1" -P --stats 30s --stats-one-line
  syncc5:
    needs : syncc4
    runs-on: ubuntu-latest
    name: Syncerrr5
    continue-on-error: true
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG1 }}
          EOF
      - name: Transferr5
        run: |
          rclone copy gdrive:"/Transfer/Sorted/TV Shows Part 2" onedrive5:"/PSA TV Part 2" -P --stats 30s --stats-one-line
